<?php

function get_token()
{
  global $user;
  $data = array('client_id' => 'abc',
    'client_secret' => 'def',
    'username' => 'chinhammk',
    'password' => '123456mk',
    'grant_type' => 'password'
  );

  $options = array(
    'method' => 'POST',
    'timeout' => 60,
    'headers' => array('Content-Type' => 'application/x-www-form-urlencoded'),
    'data' => $data,
  );
  $response = drupal_http_request('http://localhost/drupal-7.82/oauth2/token', $options);
  $result = json_decode($response->data);
  $token = $result->access_token;
  $data_token = oauth2_server_token_load($token);
  $uid = $data_token->uid;
  $user = user_load($uid);
  if ($user->uid == 1) {
    return TRUE;
  }
  return FALSE;
//    print '<pre>';
//    print_r($user);
//    print '</pre>';
//    exit();

}


function my_custom_table_menu()
{
  $items['admin/custom/my_custom_table/add'] = array(
    'title' => 'My Custom Table',
    'description' => 'View My Custom Table.',
    'page callback' => 'my_custom_table_block_view',
    'access arguments' => array('access my_custom_table'),
    'weight' => -14,
  );

  $items['admin/custom/my_custom_table/%/edit'] = array(
    'title' => 'My Custom Table',
    'description' => 'View My Custom Table.',
    'page callback' => 'my_custom_table_edit_block_view',
    'page argument' => array(3),
    'access arguments' => array('access my_custom_table'),
    'weight' => -14,
  );

  $items['admin/custom/my_custom_table/%/delete'] = array(
    'title' => 'My Custom Table',
    'description' => 'View My Custom Table.',
    'page callback' => 'my_custom_delete',
    'page argument' => array(3),
    'access arguments' => array('access my_custom_table'),
    'weight' => -14,
  );

  $items['admin/custom/my_custom_table'] = array(
    'title' => 'My Custom Table',
    'description' => 'View My Custom Table.',
    'page callback' => 'my_custom_table_sort_with_pager_content',
    'access arguments' => array('access my_custom_table'),
    'weight' => -14,
  );

  $items['admin/custom_node/node/create'] = array(
    'title' => 'Create Node',
    'description' => 'View My Custom Node.',
    'page callback' => 'my_custom_form_add',
    'access arguments' => array('access content'),
  );

  $items['admin/custom_node/node/update'] = array(
    'title' => 'Update Node',
    'description' => 'Update Custom Node.',
    'page callback' => 'my_custom_form_update',
    'access arguments' => array('access content'),
  );

  $items['admin/custom_node/node/delete'] = array(
    'title' => 'Delete Node',
    'description' => 'Delete Custom Node.',
    'page callback' => 'my_custom_form_delete',
    'access arguments' => array('access content'),
  );

  $items['admin/custom_user/user/create'] = array(
    'title' => 'Create User',
    'description' => 'Create Custom User.',
    'page callback' => 'my_custom_user_create',
    'access arguments' => array('access content'),
  );

  $items['admin/custom_user/user/update'] = array(
    'title' => 'Update User',
    'description' => 'Update Custom User.',
    'page callback' => 'my_custom_user_update',
    'access arguments' => array('access content'),
  );

  $items['admin/custom_user/user/delete'] = array(
    'title' => 'Delete User',
    'description' => 'Delete Custom User.',
    'page callback' => 'my_custom_user_delete',
    'access arguments' => array('access content'),
  );

  $items['admin/custom_taxonomy/taxonomy/create'] = array(
    'title' => 'Create Taxonomy',
    'description' => 'Create Custom Taxonomy',
    'page callback' => 'my_custom_taxonomy_create',
    'access arguments' => array('access content'),
  );

  $items['admin/custom_taxonomy/taxonomy/update'] = array(
    'title' => 'Update Taxonomy',
    'description' => 'Update Custom Taxonomy',
    'page callback' => 'my_custom_taxonomy_update',
    'access arguments' => array('access content'),
  );

  $items['admin/custom_taxonomy/taxonomy/delete'] = array(
    'title' => 'Delete Taxonomy',
    'description' => 'Delete Custom Taxonomy',
    'page callback' => 'my_custom_taxonomy_delete',
    'access arguments' => array('access content'),
  );

  $items['admin/custom_term/term/create'] = array(
    'title' => 'Create Term',
    'description' => 'Create Custom Term',
    'page callback' => 'my_custom_term_create',
    'access arguments' => array('access content'),
  );

  $items['admin/custom_term/term/update'] = array(
    'title' => 'Update Term',
    'description' => 'Update Custom Term',
    'page callback' => 'my_custom_term_update',
    'access arguments' => array('access content'),
  );

  return $items;

}


function my_custom_form_add()
{
  get_token();
  $request = OAuth2\Request::createFromGlobals();


  if (get_token() == TRUE) {
    $node = new stdClass();
    $node->type = 'article';
    node_object_prepare($node);

    $node->title = $request->request['title'];
    $node->body[LANGUAGE_NONE][0]['summary'] = $request->request['summary'];
    $node->body[LANGUAGE_NONE][0]['value'] = $request->request['body-text'];
    $node->status = 1;
    $node->body[LANGUAGE_NONE][0]['format'] = 'filtered_html';
    $node->field_category[$node->language][0]['target_id'] = $request->request['field-category'];
    $path = 'content/programmatically_created_node_' . date('YmdHis');
    $node->path = array('alias' => $path);

//    print '<pre>';
//    print_r($node);
//    print '</pre>';
//    exit();

    node_save($node);


    $data = array(
      'title' => $node->title,
      'type' => $node->type,
      'value' => $node->body[LANGUAGE_NONE][0]['value'],
      'format' => 'filtered_html'
    );
    return drupal_json_output($data);
  }

}

function my_custom_form_update()
{
  $request = OAuth2\Request::createFromGlobals();

  if (get_token() == true) {
    $nid = $request->request['nid'];
    $node = node_load($nid);
    $node->title = $request->request['title'];
    $node->body[LANGUAGE_NONE][0]['summary'] = $request->request['summary'];
    $node->body[LANGUAGE_NONE][0]['value'] = $request->request['body-text'];
//  print '<pre>';
//  print_r($node);
//  print '</pre>';
//  exit();
    node_save($node);

  }


  $data = array(
    'title' => $node->title,
    'type' => $node->type,
    'value' => $node->body[LANGUAGE_NONE][0]['value'],
    'format' => 'filtered_html'
  );
  return drupal_json_output($data);
}

function my_custom_form_delete()
{
  $request = OAuth2\Request::createFromGlobals();
//  print '<pre>';
//  print_r($request);
//  print '</pre>';
//  exit();
  if(get_token() == true){
    $nid = $request->request['nid'];
    node_delete($nid);
  }
}

require_once DRUPAL_ROOT . '/' . variable_get('password_inc', 'includes/password.inc');

function my_custom_user_create()
{
  $request = OAuth2\Request::createFromGlobals();

  if (get_token() == true){
    $account = new stdClass;
    $account->is_new = TRUE;
    $account->name = $request->request['username'];
    $account->pass = user_hash_password($request->request['password']);
    $account->mail = $request->request['e-mail'];
    $account->init = $request->request['e-mail'];
    $account->status = $request->request['status'];
    $account->roles = array(DRUPAL_AUTHENTICATED_RID => $request->request['role']);
    $account->timezone = variable_get('date_default_timezone', '');
    user_save($account);
  }
  print '<pre>';
  print_r($account);
  print '</pre>';
  exit();


}

function my_custom_user_update()
{
  $request = OAuth2\Request::createFromGlobals();

  if (get_token() ==  true) {
    $uid_user = $request->request['uid'];
    $account = user_load($uid_user);

    $account->name = $request->request['username'];
    $account->pass = user_hash_password($request->request['password']);
    $account->mail = $request->request['e-mail'];
    $account->init = $request->request['e-mail'];
    $account->status = $request->request['status'];
//    $account->roles = array(DRUPAL_AUTHENTICATED_RID => $request->request['password']);
    user_save($account);
    print '<pre>';
    print_r($account);
    print '</pre>';
    exit();

  }
}

function my_custom_user_delete()
{
  $request = OAuth2\Request::createFromGlobals();

  if (get_token() == true) {
    $uid_user = $request->request['uid'];
    $account = user_load($uid_user);
    user_delete($account->uid);
  }
}

function my_custom_taxonomy_create()
{
  $request = OAuth2\Request::createFromGlobals();


  if (get_token() == true) {
    $vocabulary = new stdClass();
    $vocabulary->name = $request->request['name'];
    $vocabulary->machine_name = $request->request['machine_name'];
    $vocabulary->description = $request->request['description'];
    $vocabulary->module = $request->request['module'];
    taxonomy_vocabulary_save($vocabulary);
    print '<pre>';
    print_r($vocabulary);
    print '</pre>';
    exit();


  }

}

function my_custom_taxonomy_update(){
  $request = OAuth2\Request::createFromGlobals();
  if (get_token() ==  true){
    $vid = $request->request['vid'];
    $vocabulary = taxonomy_vocabulary_load($vid);
    $vocabulary->name = $request->request['name'];
    $vocabulary->machine_name = $request->request['machine_name'];
    $vocabulary->description = $request->request['description'];
    taxonomy_vocabulary_save($vocabulary);
    print '<pre>';
    print_r($vocabulary);
    print '</pre>';
    exit();

  }
}

function my_custom_taxonomy_delete(){
  $request = OAuth2\Request::createFromGlobals();
  if (get_token() ==  true){
    $vid = $request->request['vid'];
    $vocabulary = taxonomy_vocabulary_load($vid);
    taxonomy_vocabulary_delete($vocabulary->vid);
  }
}

function my_custom_term_create(){
  $request = OAuth2\Request::createFromGlobals();
  if (get_token() ==  true){
    $newterm = new stdClass();
    $newterm->vid = $request->request['vid'];
    $newterm->name = $request->request['name'];
    $newterm->description = $request->request['description'];
    $newterm->parent = 0;
    taxonomy_term_save($newterm);
    print '<pre>';
    print_r($newterm);
    print '</pre>';
    exit();
  }
}

function my_custom_term_update()
{
  $request = OAuth2\Request::createFromGlobals();
  $vid = 3;
  $vocabulary = taxonomy_vocabulary_load($vid);
  $tid = 1;
  $term = taxonomy_term_load($tid);

  if (get_token() == true && $vocabulary->vid == $term->vid){
    $term->name = $request->request['name'];
    $term->description = $request->request['description'];
    $term->parent = 0;
    taxonomy_term_save($term);
    print '<pre>';
    print_r($term);
    print '</pre>';
    exit();
  }
}







